In [113]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn import linear_model
import torch
from scipy.special import softmax 
from sklearn.preprocessing import StandardScaler

In [114]:
scaler = StandardScaler()

In [115]:
#Use your own local path please!
path = "./Data/"
file_name = ["train.csv", "test.csv", "submission.csv"]
df_train = pd.read_csv(path + file_name[0])
df_test = pd.read_csv(path + file_name[1])
df_submission = pd.read_csv(path + file_name[2])

In [116]:
df_train['key'] = df_train['key'].fillna(df_train['key'].mean())

In [117]:
df_train['instrumentalness'] = df_train['instrumentalness'].fillna(df_train['instrumentalness'].mean())

In [118]:
df_train['Popularity'] = df_train['Popularity'].fillna(df_train['Popularity'].mean())

In [119]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

#def softmax(x):
#    return (np.exp(x)/np.exp(x).sum())

In [120]:
df_train_features = df_train[['Popularity', 'danceability', 'energy',
       'key', 'loudness', 'mode', 'speechiness', 'acousticness',
       'instrumentalness', 'liveness', 'valence', 'tempo',
       'duration_in min/ms', 'time_signature']].copy()
df_train_features[df_train_features.columns] = scaler.fit_transform(df_train_features)
df_train_target = df_train[['Class']].head(100).to_numpy()
df_train_features = df_train_features.head(100).to_numpy()

In [121]:
df_train_features[2]

array([-0.55245369, -0.65819005, -0.20723713,  0.01578504, -0.10455328,
        0.75529374, -0.32554479,  0.76915702, -0.6705926 ,  1.2425948 ,
        1.25231394,  0.84738275, -0.81329315,  0.21006549])

In [122]:
D = df_train_features.shape[1]
N = df_train_features.shape[0]
D,N

(14, 100)

In [123]:
np.unique(df_train_target)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64)

In [127]:
np.dot(beta, df_train_features[1,:])


-0.048215444681274755

In [131]:
np.zeros((14,11))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [142]:
softmax(np.dot(beta_array[i,:], df_train_features[90,:]))

1.0

In [153]:
p

array([0.12033714, 0.1124085 , 0.10989751, 0.12605127, 0.08752555,
       0.05473679, 0.08873692, 0.08184877, 0.05045781, 0.05640744,
       0.1115923 ])

In [169]:
# sample coefficients (beta)
beta = np.random.normal(0,1,size=D)
print("beta:", beta)

beta_array = np.zeros((11,14))

for i in range(11):
    
    beta_array[i,:] = np.random.normal(0,1,size=D)
    
# sample observations (y's)
y = np.zeros((N,11))
for n in range(N):
    
    probs = np.zeros(11)
    for i in range(11):
        probs[i] = np.array([(np.dot(beta_array[i,:], df_train_features[n,:]))])
        
    p =  softmax(probs)
    y[n,:] = np.random.multinomial(1, p)  #binomial with one trial is equivalent to bernoulli
    #y[n] = int(p > 0.5) # alternative version without observation noise
    #print(" p=, y[n]="  (n, p, y[n,:]))
    print('n, p and y ', n, p, y[n,:])

beta: [-1.35095095 -0.76149222  0.22218266 -0.08971102 -1.05924137  0.35337647
 -0.08780079  0.05451068 -1.57646609  0.50601571 -1.740342    0.99077925
  0.90679605  0.19996633]
n, p and y  0 [1.70396726e-04 7.03188447e-06 8.09596568e-02 4.38881188e-03
 6.75513290e-05 8.87313341e-01 8.33080493e-06 1.82198282e-04
 2.55231102e-02 1.19891434e-03 1.80656765e-04] [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
n, p and y  1 [0.0153865  0.00096985 0.00195139 0.13181983 0.05254882 0.03560641
 0.00085981 0.01334762 0.66908945 0.07739128 0.00102904] [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
n, p and y  2 [2.71774226e-01 7.40296255e-03 2.28454029e-02 1.41154653e-02
 1.63894571e-02 6.31251369e-01 1.67727560e-02 6.63252789e-03
 2.87926954e-04 3.14908847e-03 9.37881797e-03] [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
n, p and y  3 [2.13301118e-03 1.68118785e-03 4.30998019e-04 5.01245035e-05
 2.86630321e-05 1.02954359e-03 2.32414612e-04 8.16847823e-04
 9.58085966e-01 1.56865698e-02 1.98246740e-02] [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.

In [174]:
label_array = np.array([]) 
for i in y:
    label_array = np.append(label_array,np.argmax(i))
label_array

array([ 5.,  3.,  5.,  8.,  3.,  4.,  0.,  5.,  4.,  4.,  0.,  8.,  6.,
        2.,  8.,  9.,  0.,  3.,  6.,  3.,  4., 10., 10.,  0.,  1., 10.,
        8.,  6.,  0.,  4.,  8.,  4.,  3.,  3.,  7.,  5.,  7.,  1.,  7.,
        3.,  8.,  6.,  2.,  6., 10.,  8.,  2.,  8.,  7.,  9.,  8.,  5.,
        0.,  9.,  3.,  0.,  7.,  4.,  0.,  4.,  8.,  0.,  4.,  7.,  5.,
        7., 10., 10.,  3.,  5.,  4.,  8.,  8.,  4.,  4.,  5.,  1.,  0.,
        8.,  2.,  6.,  4.,  3.,  2.,  6.,  8.,  7.,  9.,  9.,  9.,  7.,
        4.,  3.,  1.,  8.,  2.,  8.,  3.,  4.,  5.])

In [177]:
from collections import Counter

counts = Counter(label_array)
counts



Counter({5.0: 9,
         3.0: 12,
         8.0: 16,
         4.0: 15,
         0.0: 10,
         6.0: 7,
         2.0: 6,
         9.0: 6,
         10.0: 6,
         1.0: 4,
         7.0: 9})

In [ ]:
# assume sigma and tau to be fixed
tau = 0.1
print("tau:", tau)
sigma = 0.05
print("sigma:", sigma)

# length of the time-series
T = 20

z = np.zeros(T) # vector to store sampled latent states
y = np.zeros(T) # vector to store sampled observations

# sample coefficient (beta)
beta = np.random.normal(0,0.1)
print("beta:", beta)

# sample latent states (z)
z[0] = np.random.normal(0,1) # first state is sampled separately
for t in range(1,T):
    z[t] = np.random.normal(beta * z[t-1], tau)
print("z:", z)
    
# sample observations (y)
for t in range(T):
    y[t] = np.random.normal(z[t], sigma)
print("y:", y)

In [ ]:
# Model definition
def model(X, obs=None):
    alpha = pyro.sample("alpha", dist.Normal(0., 1.))                   # Prior for the bias/intercept
    beta  = pyro.sample("beta", dist.Normal(torch.zeros(X.shape[1]), 
                                            torch.ones(X.shape[1])))    # Priors for the regression coeffcients
    sigma = pyro.sample("sigma", dist.HalfCauchy(5.))                   # Prior for the variance
    
    with pyro.plate("data"):
        y = pyro.sample("y", dist.Normal(alpha + X.matmul(beta), sigma), obs=obs)
        
    return y